Fixes #197
cord-network/cord.js pull request #203
Opened 2024-04-12 20:22 UTC by hardiksharma11

Fixes #197

2024-04-13 05:06 UTC, hardiksharma11 commented
@vatsa287 @amarts @NiranjanAP will you please review

2024-04-16 14:23 UTC, hardiksharma11 commented
@vatsa287  @amarts  @NiranjanAP  PTAL

2024-04-17 08:23 UTC, vatsa287 approved these changes
LGTM

2024-04-17 08:23 UTC, vatsa287 commented on packages/chain-space/src/ChainSpace.chain.ts
> +      `Error preparing extrinsic for creation: "${error}".`
nit: Error preparing extrinsic for creation of chainspace

2024-04-17 10:08 UTC, hardiksharma11 commented on packages/chain-space/src/ChainSpace.chain.ts
> +      `Error preparing extrinsic for creation: "${error}".`
Done

2024-04-22 08:52 UTC, vatsa287 requested changes
Minor Comment:
Please move `prepare....` method above `dispatch...` method.

2024-04-22 11:07 UTC, hardiksharma11 commented
@vatsa287 done the required change

2024-04-22 11:34 UTC, vatsa287 approved these changes
LGTM

2024-04-29 09:56 UTC, merged